version: "3"

services:
  api:
    image: wsbackend-api:latest
    hostname: ws-api
    build:
      context: .
      dockerfile: api.dockerfile
    links:
      - elasticsearch
    ports:
      - "8000:8000"
  tasknode:
    image: wsbackend-tasknode:latest
    build:
      context: .
      dockerfile: tasknode.dockerfile
    links:
      - elasticsearch
  redis:
    image: redis:latest
    hostname: ws-redis
  elasticsearch:
    image: elasticsearch:latest
    hostname: ws-elasticsearch
    volumes:
      - "./data/elasticsearch:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: ws-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=wsuser
      - RABBITMQ_DEFAULT_PASS=wspassword
      - RABBITMQ_DEFAULT_VHOST=wsvhost
  frontend:
    image: wsfrontend:latest
    hostname: ws-frontend
    build:
      context: .
      dockerfile: frontend.dockerfile
    links:
      - elasticsearch
    ports:
      - "8443:443"
